[env]
# 公共配置，会被下面的具体环境继承
platform = espressif32
board = esp32dev
monitor_speed = 115200
upload_speed = 921600

[env:arduino]
board_build.partitions = huge_app.csv
framework = arduino
build_flags =
  -D USE_ARDUINO
  ; 需要查看启动初始化细节时，取消下一行注释
  ; -D FW_DEBUG_LOG=1
lib_deps = bblanchon/ArduinoJson @ ^6.21.0

