[env]
# 公共配置，会被下面的具体环境继承
platform = espressif32
board = esp32dev
monitor_speed = 115200
upload_speed = 921600

[env:arduino]
board_build.partitions = huge_app.csv
framework = arduino
build_flags = -D USE_ARDUINO
lib_deps = bblanchon/ArduinoJson @ ^6.21.0

